### PR TITLE
French grammar/spelling/syntax improvements

### PR DESCRIPTION
**Pull request by Philip-Nicolas**
Certain strings in translations.json still blank: Lack of english text documenting what those strings **should** say, couldn't find them in the source code.

### CODE REVIEW

**Comment by henry232323** [comment]
Yeah I need to document that and make a proper english sheet. Its all pulled fairly regularly from the source in no particular order.

**Comment by Philip-Nicolas** [comment]
I would recommend implementing a formal localization system, if you really want to add more language support in the future.

**Comment by henry232323** [comment]
Im getting all these translations, but the actual implementation for translation isn't complete yet...

**Comment by Philip-Nicolas** [comment]
That's what happens when u add the hacktoberfest label lmao

**Comment by Philip-Nicolas** [comment]
There might be a library for localization, but i am not familiar with python programming in general. GL though!

**Comment by henry232323** [comment]
Yeah I guess. I'm sure there is, but really the hardest part is actually implementing the translations

**Comment by Philip-Nicolas** [comment]
That's why I suggest you look up python localization libraries, they can help you with the implementation of translations.

**Comment by henry232323** [comment]
I mean foremost actually adding the server configurations and databasing for that part

**Pull request merged**
